// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBdCjE2UrBHCyO_oKQ0PWuiKd5SSRglNN8',
    appId: '1:367487014785:web:047e3f462aa06c8e453a80',
    messagingSenderId: '367487014785',
    projectId: 'neww-3dd55',
    authDomain: 'neww-3dd55.firebaseapp.com',
    storageBucket: 'neww-3dd55.firebasestorage.app',
    measurementId: 'G-85JEVBJGNV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC1hsmHEjhmHaQ9WeDuhWFOTDGiv6wCPxc',
    appId: '1:367487014785:android:0bd6c8fa06eaa222453a80',
    messagingSenderId: '367487014785',
    projectId: 'neww-3dd55',
    storageBucket: 'neww-3dd55.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAjjraF-AhuV3cl_Rsp6cvXIpV3LDRlaWc',
    appId: '1:367487014785:ios:0f98795a9957a984453a80',
    messagingSenderId: '367487014785',
    projectId: 'neww-3dd55',
    storageBucket: 'neww-3dd55.firebasestorage.app',
    iosBundleId: 'com.example.newproject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAjjraF-AhuV3cl_Rsp6cvXIpV3LDRlaWc',
    appId: '1:367487014785:ios:0f98795a9957a984453a80',
    messagingSenderId: '367487014785',
    projectId: 'neww-3dd55',
    storageBucket: 'neww-3dd55.firebasestorage.app',
    iosBundleId: 'com.example.newproject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBdCjE2UrBHCyO_oKQ0PWuiKd5SSRglNN8',
    appId: '1:367487014785:web:d68e01cb0dc56f7f453a80',
    messagingSenderId: '367487014785',
    projectId: 'neww-3dd55',
    authDomain: 'neww-3dd55.firebaseapp.com',
    storageBucket: 'neww-3dd55.firebasestorage.app',
    measurementId: 'G-4C21F7WXTM',
  );
}
